/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.User;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class Account   {
  @SerializedName("privateData")
  private Map<String, String> privateData = new HashMap<String, String>();

  @SerializedName("data")
  private Map<String, String> data = new HashMap<String, String>();

  @SerializedName("defaultUserId")
  private String defaultUserId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("defaultUser")
  private User defaultUser = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("WaitingAprove")
    WAITINGAPROVE("WaitingAprove"),
    
    @SerializedName("Approved")
    APPROVED("Approved");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("typ")
  private String typ = null;

  public Account privateData(Map<String, String> privateData) {
    this.privateData = privateData;
    return this;
  }

  public Account putPrivateDataItem(String key, String privateDataItem) {
    this.privateData.put(key, privateDataItem);
    return this;
  }

   /**
   * Get privateData
   * @return privateData
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getPrivateData() {
    return privateData;
  }

  public void setPrivateData(Map<String, String> privateData) {
    this.privateData = privateData;
  }

  public Account data(Map<String, String> data) {
    this.data = data;
    return this;
  }

  public Account putDataItem(String key, String dataItem) {
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getData() {
    return data;
  }

  public void setData(Map<String, String> data) {
    this.data = data;
  }

  public Account defaultUserId(String defaultUserId) {
    this.defaultUserId = defaultUserId;
    return this;
  }

   /**
   * Get defaultUserId
   * @return defaultUserId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultUserId() {
    return defaultUserId;
  }

  public void setDefaultUserId(String defaultUserId) {
    this.defaultUserId = defaultUserId;
  }

  public Account id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Account defaultUser(User defaultUser) {
    this.defaultUser = defaultUser;
    return this;
  }

   /**
   * Get defaultUser
   * @return defaultUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getDefaultUser() {
    return defaultUser;
  }

  public void setDefaultUser(User defaultUser) {
    this.defaultUser = defaultUser;
  }

  public Account status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Account typ(String typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTyp() {
    return typ;
  }

  public void setTyp(String typ) {
    this.typ = typ;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.privateData, account.privateData) &&
        Objects.equals(this.data, account.data) &&
        Objects.equals(this.defaultUserId, account.defaultUserId) &&
        Objects.equals(this.id, account.id) &&
        Objects.equals(this.defaultUser, account.defaultUser) &&
        Objects.equals(this.status, account.status) &&
        Objects.equals(this.typ, account.typ);
  }

  @Override
  public int hashCode() {
    return Objects.hash(privateData, data, defaultUserId, id, defaultUser, status, typ);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    privateData: ").append(toIndentedString(privateData)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    defaultUserId: ").append(toIndentedString(defaultUserId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    defaultUser: ").append(toIndentedString(defaultUser)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

