/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class CustomerPlanPeriod   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("numberPackPeriod_inPlanPeriod")
  private Long numberPackPeriodInPlanPeriod = null;

  @SerializedName("totalInPayment")
  private Map<String, Long> totalInPayment = new HashMap<String, Long>();

  public CustomerPlanPeriod id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerPlanPeriod numberPackPeriodInPlanPeriod(Long numberPackPeriodInPlanPeriod) {
    this.numberPackPeriodInPlanPeriod = numberPackPeriodInPlanPeriod;
    return this;
  }

   /**
   * Get numberPackPeriodInPlanPeriod
   * @return numberPackPeriodInPlanPeriod
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumberPackPeriodInPlanPeriod() {
    return numberPackPeriodInPlanPeriod;
  }

  public void setNumberPackPeriodInPlanPeriod(Long numberPackPeriodInPlanPeriod) {
    this.numberPackPeriodInPlanPeriod = numberPackPeriodInPlanPeriod;
  }

  public CustomerPlanPeriod totalInPayment(Map<String, Long> totalInPayment) {
    this.totalInPayment = totalInPayment;
    return this;
  }

  public CustomerPlanPeriod putTotalInPaymentItem(String key, Long totalInPaymentItem) {
    this.totalInPayment.put(key, totalInPaymentItem);
    return this;
  }

   /**
   * Get totalInPayment
   * @return totalInPayment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Long> getTotalInPayment() {
    return totalInPayment;
  }

  public void setTotalInPayment(Map<String, Long> totalInPayment) {
    this.totalInPayment = totalInPayment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerPlanPeriod customerPlanPeriod = (CustomerPlanPeriod) o;
    return Objects.equals(this.id, customerPlanPeriod.id) &&
        Objects.equals(this.numberPackPeriodInPlanPeriod, customerPlanPeriod.numberPackPeriodInPlanPeriod) &&
        Objects.equals(this.totalInPayment, customerPlanPeriod.totalInPayment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, numberPackPeriodInPlanPeriod, totalInPayment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerPlanPeriod {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    numberPackPeriodInPlanPeriod: ").append(toIndentedString(numberPackPeriodInPlanPeriod)).append("\n");
    sb.append("    totalInPayment: ").append(toIndentedString(totalInPayment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

