/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class CustomerPlan   {
  @SerializedName("currentBillId")
  private String currentBillId = null;

  @SerializedName("endDate")
  private Long endDate = null;

  @SerializedName("endPeriodToPlanId")
  private String endPeriodToPlanId = null;

  @SerializedName("swapPlanId")
  private String swapPlanId = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("packId")
  private String packId = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("History")
    HISTORY("History"),
    
    @SerializedName("Enjoy")
    ENJOY("Enjoy");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("totalInPayment")
  private Map<String, Long> totalInPayment = new HashMap<String, Long>();

  @SerializedName("planId")
  private String planId = null;

  @SerializedName("family")
  private String family = null;

  @SerializedName("onExpirePlanId")
  private String onExpirePlanId = null;

  @SerializedName("startDate")
  private Long startDate = null;

  public CustomerPlan currentBillId(String currentBillId) {
    this.currentBillId = currentBillId;
    return this;
  }

   /**
   * Get currentBillId
   * @return currentBillId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrentBillId() {
    return currentBillId;
  }

  public void setCurrentBillId(String currentBillId) {
    this.currentBillId = currentBillId;
  }

  public CustomerPlan endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public CustomerPlan endPeriodToPlanId(String endPeriodToPlanId) {
    this.endPeriodToPlanId = endPeriodToPlanId;
    return this;
  }

   /**
   * Get endPeriodToPlanId
   * @return endPeriodToPlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndPeriodToPlanId() {
    return endPeriodToPlanId;
  }

  public void setEndPeriodToPlanId(String endPeriodToPlanId) {
    this.endPeriodToPlanId = endPeriodToPlanId;
  }

  public CustomerPlan swapPlanId(String swapPlanId) {
    this.swapPlanId = swapPlanId;
    return this;
  }

   /**
   * Get swapPlanId
   * @return swapPlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSwapPlanId() {
    return swapPlanId;
  }

  public void setSwapPlanId(String swapPlanId) {
    this.swapPlanId = swapPlanId;
  }

  public CustomerPlan customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CustomerPlan id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerPlan packId(String packId) {
    this.packId = packId;
    return this;
  }

   /**
   * Get packId
   * @return packId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPackId() {
    return packId;
  }

  public void setPackId(String packId) {
    this.packId = packId;
  }

  public CustomerPlan status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CustomerPlan totalInPayment(Map<String, Long> totalInPayment) {
    this.totalInPayment = totalInPayment;
    return this;
  }

  public CustomerPlan putTotalInPaymentItem(String key, Long totalInPaymentItem) {
    this.totalInPayment.put(key, totalInPaymentItem);
    return this;
  }

   /**
   * Get totalInPayment
   * @return totalInPayment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Long> getTotalInPayment() {
    return totalInPayment;
  }

  public void setTotalInPayment(Map<String, Long> totalInPayment) {
    this.totalInPayment = totalInPayment;
  }

  public CustomerPlan planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public CustomerPlan family(String family) {
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFamily() {
    return family;
  }

  public void setFamily(String family) {
    this.family = family;
  }

  public CustomerPlan onExpirePlanId(String onExpirePlanId) {
    this.onExpirePlanId = onExpirePlanId;
    return this;
  }

   /**
   * Get onExpirePlanId
   * @return onExpirePlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOnExpirePlanId() {
    return onExpirePlanId;
  }

  public void setOnExpirePlanId(String onExpirePlanId) {
    this.onExpirePlanId = onExpirePlanId;
  }

  public CustomerPlan startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerPlan customerPlan = (CustomerPlan) o;
    return Objects.equals(this.currentBillId, customerPlan.currentBillId) &&
        Objects.equals(this.endDate, customerPlan.endDate) &&
        Objects.equals(this.endPeriodToPlanId, customerPlan.endPeriodToPlanId) &&
        Objects.equals(this.swapPlanId, customerPlan.swapPlanId) &&
        Objects.equals(this.customerId, customerPlan.customerId) &&
        Objects.equals(this.id, customerPlan.id) &&
        Objects.equals(this.packId, customerPlan.packId) &&
        Objects.equals(this.status, customerPlan.status) &&
        Objects.equals(this.totalInPayment, customerPlan.totalInPayment) &&
        Objects.equals(this.planId, customerPlan.planId) &&
        Objects.equals(this.family, customerPlan.family) &&
        Objects.equals(this.onExpirePlanId, customerPlan.onExpirePlanId) &&
        Objects.equals(this.startDate, customerPlan.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentBillId, endDate, endPeriodToPlanId, swapPlanId, customerId, id, packId, status, totalInPayment, planId, family, onExpirePlanId, startDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerPlan {\n");
    
    sb.append("    currentBillId: ").append(toIndentedString(currentBillId)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    endPeriodToPlanId: ").append(toIndentedString(endPeriodToPlanId)).append("\n");
    sb.append("    swapPlanId: ").append(toIndentedString(swapPlanId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    packId: ").append(toIndentedString(packId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalInPayment: ").append(toIndentedString(totalInPayment)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    onExpirePlanId: ").append(toIndentedString(onExpirePlanId)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

