/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class CustomerPackSubscription   {
  @SerializedName("closedTime")
  private Long closedTime = null;

  @SerializedName("currentEnjoyId")
  private String currentEnjoyId = null;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    @SerializedName("History")
    HISTORY("History"),
    
    @SerializedName("Enjoy")
    ENJOY("Enjoy");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("packId")
  private String packId = null;

  @SerializedName("creationTime")
  private Long creationTime = null;

  public CustomerPackSubscription closedTime(Long closedTime) {
    this.closedTime = closedTime;
    return this;
  }

   /**
   * Get closedTime
   * @return closedTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getClosedTime() {
    return closedTime;
  }

  public void setClosedTime(Long closedTime) {
    this.closedTime = closedTime;
  }

  public CustomerPackSubscription currentEnjoyId(String currentEnjoyId) {
    this.currentEnjoyId = currentEnjoyId;
    return this;
  }

   /**
   * Get currentEnjoyId
   * @return currentEnjoyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrentEnjoyId() {
    return currentEnjoyId;
  }

  public void setCurrentEnjoyId(String currentEnjoyId) {
    this.currentEnjoyId = currentEnjoyId;
  }

  public CustomerPackSubscription state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public CustomerPackSubscription customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CustomerPackSubscription id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerPackSubscription packId(String packId) {
    this.packId = packId;
    return this;
  }

   /**
   * Get packId
   * @return packId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPackId() {
    return packId;
  }

  public void setPackId(String packId) {
    this.packId = packId;
  }

  public CustomerPackSubscription creationTime(Long creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(Long creationTime) {
    this.creationTime = creationTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerPackSubscription customerPackSubscription = (CustomerPackSubscription) o;
    return Objects.equals(this.closedTime, customerPackSubscription.closedTime) &&
        Objects.equals(this.currentEnjoyId, customerPackSubscription.currentEnjoyId) &&
        Objects.equals(this.state, customerPackSubscription.state) &&
        Objects.equals(this.customerId, customerPackSubscription.customerId) &&
        Objects.equals(this.id, customerPackSubscription.id) &&
        Objects.equals(this.packId, customerPackSubscription.packId) &&
        Objects.equals(this.creationTime, customerPackSubscription.creationTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closedTime, currentEnjoyId, state, customerId, id, packId, creationTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerPackSubscription {\n");
    
    sb.append("    closedTime: ").append(toIndentedString(closedTime)).append("\n");
    sb.append("    currentEnjoyId: ").append(toIndentedString(currentEnjoyId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    packId: ").append(toIndentedString(packId)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

