/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class CustomerBill   {
  @SerializedName("customerPlanId")
  private String customerPlanId = null;

  @SerializedName("creationTimespan")
  private Long creationTimespan = null;

  @SerializedName("lasUpdateTimespan")
  private Long lasUpdateTimespan = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("id")
  private String id = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("S3Forgiven")
    S3FORGIVEN("S3Forgiven"),
    
    @SerializedName("S4Paid")
    S4PAID("S4Paid"),
    
    @SerializedName("S1WaitingPayment")
    S1WAITINGPAYMENT("S1WaitingPayment"),
    
    @SerializedName("S2WaitingPlanExpiration")
    S2WAITINGPLANEXPIRATION("S2WaitingPlanExpiration");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("totalInPayment")
  private Map<String, Long> totalInPayment = new HashMap<String, Long>();

  @SerializedName("planId")
  private String planId = null;

  public CustomerBill customerPlanId(String customerPlanId) {
    this.customerPlanId = customerPlanId;
    return this;
  }

   /**
   * Get customerPlanId
   * @return customerPlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerPlanId() {
    return customerPlanId;
  }

  public void setCustomerPlanId(String customerPlanId) {
    this.customerPlanId = customerPlanId;
  }

  public CustomerBill creationTimespan(Long creationTimespan) {
    this.creationTimespan = creationTimespan;
    return this;
  }

   /**
   * Get creationTimespan
   * @return creationTimespan
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreationTimespan() {
    return creationTimespan;
  }

  public void setCreationTimespan(Long creationTimespan) {
    this.creationTimespan = creationTimespan;
  }

  public CustomerBill lasUpdateTimespan(Long lasUpdateTimespan) {
    this.lasUpdateTimespan = lasUpdateTimespan;
    return this;
  }

   /**
   * Get lasUpdateTimespan
   * @return lasUpdateTimespan
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLasUpdateTimespan() {
    return lasUpdateTimespan;
  }

  public void setLasUpdateTimespan(Long lasUpdateTimespan) {
    this.lasUpdateTimespan = lasUpdateTimespan;
  }

  public CustomerBill customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CustomerBill id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerBill status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CustomerBill totalInPayment(Map<String, Long> totalInPayment) {
    this.totalInPayment = totalInPayment;
    return this;
  }

  public CustomerBill putTotalInPaymentItem(String key, Long totalInPaymentItem) {
    this.totalInPayment.put(key, totalInPaymentItem);
    return this;
  }

   /**
   * Get totalInPayment
   * @return totalInPayment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Long> getTotalInPayment() {
    return totalInPayment;
  }

  public void setTotalInPayment(Map<String, Long> totalInPayment) {
    this.totalInPayment = totalInPayment;
  }

  public CustomerBill planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerBill customerBill = (CustomerBill) o;
    return Objects.equals(this.customerPlanId, customerBill.customerPlanId) &&
        Objects.equals(this.creationTimespan, customerBill.creationTimespan) &&
        Objects.equals(this.lasUpdateTimespan, customerBill.lasUpdateTimespan) &&
        Objects.equals(this.customerId, customerBill.customerId) &&
        Objects.equals(this.id, customerBill.id) &&
        Objects.equals(this.status, customerBill.status) &&
        Objects.equals(this.totalInPayment, customerBill.totalInPayment) &&
        Objects.equals(this.planId, customerBill.planId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerPlanId, creationTimespan, lasUpdateTimespan, customerId, id, status, totalInPayment, planId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerBill {\n");
    
    sb.append("    customerPlanId: ").append(toIndentedString(customerPlanId)).append("\n");
    sb.append("    creationTimespan: ").append(toIndentedString(creationTimespan)).append("\n");
    sb.append("    lasUpdateTimespan: ").append(toIndentedString(lasUpdateTimespan)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalInPayment: ").append(toIndentedString(totalInPayment)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

