/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class Pack   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("subscriptible")
  private Boolean subscriptible = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("resources")
  private Map<String, Integer> resources = new HashMap<String, Integer>();

  /**
   * Gets or Sets expiration
   */
  public enum ExpirationEnum {
    @SerializedName("Month")
    MONTH("Month"),
    
    @SerializedName("Year")
    YEAR("Year"),
    
    @SerializedName("Day")
    DAY("Day"),
    
    @SerializedName("Week")
    WEEK("Week"),
    
    @SerializedName("Infinity")
    INFINITY("Infinity");

    private String value;

    ExpirationEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("expiration")
  private ExpirationEnum expiration = null;

  public Pack name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Pack description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Pack subscriptible(Boolean subscriptible) {
    this.subscriptible = subscriptible;
    return this;
  }

   /**
   * Get subscriptible
   * @return subscriptible
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSubscriptible() {
    return subscriptible;
  }

  public void setSubscriptible(Boolean subscriptible) {
    this.subscriptible = subscriptible;
  }

  public Pack id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Pack resources(Map<String, Integer> resources) {
    this.resources = resources;
    return this;
  }

  public Pack putResourcesItem(String key, Integer resourcesItem) {
    this.resources.put(key, resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Integer> getResources() {
    return resources;
  }

  public void setResources(Map<String, Integer> resources) {
    this.resources = resources;
  }

  public Pack expiration(ExpirationEnum expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @ApiModelProperty(example = "null", value = "")
  public ExpirationEnum getExpiration() {
    return expiration;
  }

  public void setExpiration(ExpirationEnum expiration) {
    this.expiration = expiration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pack pack = (Pack) o;
    return Objects.equals(this.name, pack.name) &&
        Objects.equals(this.description, pack.description) &&
        Objects.equals(this.subscriptible, pack.subscriptible) &&
        Objects.equals(this.id, pack.id) &&
        Objects.equals(this.resources, pack.resources) &&
        Objects.equals(this.expiration, pack.expiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, subscriptible, id, resources, expiration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pack {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subscriptible: ").append(toIndentedString(subscriptible)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

