/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PaymentPaypal;
import io.swagger.client.model.StripeConf;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class PaymentConf   {
  @SerializedName("paypal")
  private PaymentPaypal paypal = null;

  @SerializedName("stripe")
  private StripeConf stripe = null;

  public PaymentConf paypal(PaymentPaypal paypal) {
    this.paypal = paypal;
    return this;
  }

   /**
   * Get paypal
   * @return paypal
  **/
  @ApiModelProperty(example = "null", value = "")
  public PaymentPaypal getPaypal() {
    return paypal;
  }

  public void setPaypal(PaymentPaypal paypal) {
    this.paypal = paypal;
  }

  public PaymentConf stripe(StripeConf stripe) {
    this.stripe = stripe;
    return this;
  }

   /**
   * Get stripe
   * @return stripe
  **/
  @ApiModelProperty(example = "null", value = "")
  public StripeConf getStripe() {
    return stripe;
  }

  public void setStripe(StripeConf stripe) {
    this.stripe = stripe;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentConf paymentConf = (PaymentConf) o;
    return Objects.equals(this.paypal, paymentConf.paypal) &&
        Objects.equals(this.stripe, paymentConf.stripe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paypal, stripe);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentConf {\n");
    
    sb.append("    paypal: ").append(toIndentedString(paypal)).append("\n");
    sb.append("    stripe: ").append(toIndentedString(stripe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

