/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Price;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class PaymentRequest   {
  @SerializedName("creationTimespan")
  private Long creationTimespan = null;

  @SerializedName("paidTimespan")
  private Long paidTimespan = null;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    @SerializedName("status2WaitPayment")
    STATUS2WAITPAYMENT("status2WaitPayment"),
    
    @SerializedName("status3Canceled")
    STATUS3CANCELED("status3Canceled"),
    
    @SerializedName("status4Paid")
    STATUS4PAID("status4Paid"),
    
    @SerializedName("status1Failed")
    STATUS1FAILED("status1Failed"),
    
    @SerializedName("status3Paid")
    STATUS3PAID("status3Paid");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("whatPays")
  private Map<String, Long> whatPays = new HashMap<String, Long>();

  @SerializedName("price")
  private Price price = null;

  @SerializedName("billId")
  private String billId = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("stripeChargeId")
  private String stripeChargeId = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("value")
  private Long value = null;

  public PaymentRequest creationTimespan(Long creationTimespan) {
    this.creationTimespan = creationTimespan;
    return this;
  }

   /**
   * Get creationTimespan
   * @return creationTimespan
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreationTimespan() {
    return creationTimespan;
  }

  public void setCreationTimespan(Long creationTimespan) {
    this.creationTimespan = creationTimespan;
  }

  public PaymentRequest paidTimespan(Long paidTimespan) {
    this.paidTimespan = paidTimespan;
    return this;
  }

   /**
   * Get paidTimespan
   * @return paidTimespan
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPaidTimespan() {
    return paidTimespan;
  }

  public void setPaidTimespan(Long paidTimespan) {
    this.paidTimespan = paidTimespan;
  }

  public PaymentRequest state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public PaymentRequest whatPays(Map<String, Long> whatPays) {
    this.whatPays = whatPays;
    return this;
  }

  public PaymentRequest putWhatPaysItem(String key, Long whatPaysItem) {
    this.whatPays.put(key, whatPaysItem);
    return this;
  }

   /**
   * Get whatPays
   * @return whatPays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Long> getWhatPays() {
    return whatPays;
  }

  public void setWhatPays(Map<String, Long> whatPays) {
    this.whatPays = whatPays;
  }

  public PaymentRequest price(Price price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "")
  public Price getPrice() {
    return price;
  }

  public void setPrice(Price price) {
    this.price = price;
  }

  public PaymentRequest billId(String billId) {
    this.billId = billId;
    return this;
  }

   /**
   * Get billId
   * @return billId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillId() {
    return billId;
  }

  public void setBillId(String billId) {
    this.billId = billId;
  }

  public PaymentRequest customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public PaymentRequest id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PaymentRequest stripeChargeId(String stripeChargeId) {
    this.stripeChargeId = stripeChargeId;
    return this;
  }

   /**
   * Get stripeChargeId
   * @return stripeChargeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStripeChargeId() {
    return stripeChargeId;
  }

  public void setStripeChargeId(String stripeChargeId) {
    this.stripeChargeId = stripeChargeId;
  }

  public PaymentRequest currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public PaymentRequest value(Long value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getValue() {
    return value;
  }

  public void setValue(Long value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequest paymentRequest = (PaymentRequest) o;
    return Objects.equals(this.creationTimespan, paymentRequest.creationTimespan) &&
        Objects.equals(this.paidTimespan, paymentRequest.paidTimespan) &&
        Objects.equals(this.state, paymentRequest.state) &&
        Objects.equals(this.whatPays, paymentRequest.whatPays) &&
        Objects.equals(this.price, paymentRequest.price) &&
        Objects.equals(this.billId, paymentRequest.billId) &&
        Objects.equals(this.customerId, paymentRequest.customerId) &&
        Objects.equals(this.id, paymentRequest.id) &&
        Objects.equals(this.stripeChargeId, paymentRequest.stripeChargeId) &&
        Objects.equals(this.currency, paymentRequest.currency) &&
        Objects.equals(this.value, paymentRequest.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationTimespan, paidTimespan, state, whatPays, price, billId, customerId, id, stripeChargeId, currency, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequest {\n");
    
    sb.append("    creationTimespan: ").append(toIndentedString(creationTimespan)).append("\n");
    sb.append("    paidTimespan: ").append(toIndentedString(paidTimespan)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    whatPays: ").append(toIndentedString(whatPays)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    billId: ").append(toIndentedString(billId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stripeChargeId: ").append(toIndentedString(stripeChargeId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

