/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OneTimePay;
import io.swagger.client.model.Subscription;
import io.swagger.client.model.VariableCost;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class Plan   {
  @SerializedName("variableCost")
  private Map<String, VariableCost> variableCost = new HashMap<String, VariableCost>();

  @SerializedName("name")
  private String name = null;

  @SerializedName("oneTimePay")
  private OneTimePay oneTimePay = null;

  @SerializedName("hasVariableCost")
  private Boolean hasVariableCost = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("subscription")
  private Subscription subscription = null;

  @SerializedName("beforePlanId")
  private String beforePlanId = null;

  @SerializedName("onExpiratyNextPlanId")
  private String onExpiratyNextPlanId = null;

  @SerializedName("upgradeLevel")
  private Integer upgradeLevel = null;

  @SerializedName("requirePaymentMethod")
  private Boolean requirePaymentMethod = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("packId")
  private String packId = null;

  /**
   * Gets or Sets typ
   */
  public enum TypEnum {
    @SerializedName("OneTimePay")
    ONETIMEPAY("OneTimePay"),
    
    @SerializedName("Subscription")
    SUBSCRIPTION("Subscription");

    private String value;

    TypEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("typ")
  private TypEnum typ = null;

  @SerializedName("uiOrder")
  private Integer uiOrder = null;

  @SerializedName("family")
  private String family = null;

  @SerializedName("uiVisible")
  private Boolean uiVisible = null;

  @SerializedName("withfamily")
  private Boolean withfamily = null;

  /**
   * Gets or Sets variableCostWhenPay
   */
  public enum VariableCostWhenPayEnum {
    @SerializedName("EachEndPeriod")
    EACHENDPERIOD("EachEndPeriod"),
    
    @SerializedName("EachMonth")
    EACHMONTH("EachMonth"),
    
    @SerializedName("EachWeek")
    EACHWEEK("EachWeek"),
    
    @SerializedName("EachDay")
    EACHDAY("EachDay");

    private String value;

    VariableCostWhenPayEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("variableCostWhenPay")
  private VariableCostWhenPayEnum variableCostWhenPay = null;

  @SerializedName("oneTimePlan")
  private Boolean oneTimePlan = null;

  public Plan variableCost(Map<String, VariableCost> variableCost) {
    this.variableCost = variableCost;
    return this;
  }

  public Plan putVariableCostItem(String key, VariableCost variableCostItem) {
    this.variableCost.put(key, variableCostItem);
    return this;
  }

   /**
   * Get variableCost
   * @return variableCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, VariableCost> getVariableCost() {
    return variableCost;
  }

  public void setVariableCost(Map<String, VariableCost> variableCost) {
    this.variableCost = variableCost;
  }

  public Plan name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Plan oneTimePay(OneTimePay oneTimePay) {
    this.oneTimePay = oneTimePay;
    return this;
  }

   /**
   * Get oneTimePay
   * @return oneTimePay
  **/
  @ApiModelProperty(example = "null", value = "")
  public OneTimePay getOneTimePay() {
    return oneTimePay;
  }

  public void setOneTimePay(OneTimePay oneTimePay) {
    this.oneTimePay = oneTimePay;
  }

  public Plan hasVariableCost(Boolean hasVariableCost) {
    this.hasVariableCost = hasVariableCost;
    return this;
  }

   /**
   * Get hasVariableCost
   * @return hasVariableCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasVariableCost() {
    return hasVariableCost;
  }

  public void setHasVariableCost(Boolean hasVariableCost) {
    this.hasVariableCost = hasVariableCost;
  }

  public Plan description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Plan subscription(Subscription subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @ApiModelProperty(example = "null", value = "")
  public Subscription getSubscription() {
    return subscription;
  }

  public void setSubscription(Subscription subscription) {
    this.subscription = subscription;
  }

  public Plan beforePlanId(String beforePlanId) {
    this.beforePlanId = beforePlanId;
    return this;
  }

   /**
   * Get beforePlanId
   * @return beforePlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBeforePlanId() {
    return beforePlanId;
  }

  public void setBeforePlanId(String beforePlanId) {
    this.beforePlanId = beforePlanId;
  }

  public Plan onExpiratyNextPlanId(String onExpiratyNextPlanId) {
    this.onExpiratyNextPlanId = onExpiratyNextPlanId;
    return this;
  }

   /**
   * Get onExpiratyNextPlanId
   * @return onExpiratyNextPlanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOnExpiratyNextPlanId() {
    return onExpiratyNextPlanId;
  }

  public void setOnExpiratyNextPlanId(String onExpiratyNextPlanId) {
    this.onExpiratyNextPlanId = onExpiratyNextPlanId;
  }

  public Plan upgradeLevel(Integer upgradeLevel) {
    this.upgradeLevel = upgradeLevel;
    return this;
  }

   /**
   * Get upgradeLevel
   * @return upgradeLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUpgradeLevel() {
    return upgradeLevel;
  }

  public void setUpgradeLevel(Integer upgradeLevel) {
    this.upgradeLevel = upgradeLevel;
  }

  public Plan requirePaymentMethod(Boolean requirePaymentMethod) {
    this.requirePaymentMethod = requirePaymentMethod;
    return this;
  }

   /**
   * Get requirePaymentMethod
   * @return requirePaymentMethod
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getRequirePaymentMethod() {
    return requirePaymentMethod;
  }

  public void setRequirePaymentMethod(Boolean requirePaymentMethod) {
    this.requirePaymentMethod = requirePaymentMethod;
  }

  public Plan id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Plan packId(String packId) {
    this.packId = packId;
    return this;
  }

   /**
   * Get packId
   * @return packId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPackId() {
    return packId;
  }

  public void setPackId(String packId) {
    this.packId = packId;
  }

  public Plan typ(TypEnum typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypEnum getTyp() {
    return typ;
  }

  public void setTyp(TypEnum typ) {
    this.typ = typ;
  }

  public Plan uiOrder(Integer uiOrder) {
    this.uiOrder = uiOrder;
    return this;
  }

   /**
   * Get uiOrder
   * @return uiOrder
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUiOrder() {
    return uiOrder;
  }

  public void setUiOrder(Integer uiOrder) {
    this.uiOrder = uiOrder;
  }

  public Plan family(String family) {
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFamily() {
    return family;
  }

  public void setFamily(String family) {
    this.family = family;
  }

  public Plan uiVisible(Boolean uiVisible) {
    this.uiVisible = uiVisible;
    return this;
  }

   /**
   * Get uiVisible
   * @return uiVisible
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUiVisible() {
    return uiVisible;
  }

  public void setUiVisible(Boolean uiVisible) {
    this.uiVisible = uiVisible;
  }

  public Plan withfamily(Boolean withfamily) {
    this.withfamily = withfamily;
    return this;
  }

   /**
   * Get withfamily
   * @return withfamily
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getWithfamily() {
    return withfamily;
  }

  public void setWithfamily(Boolean withfamily) {
    this.withfamily = withfamily;
  }

  public Plan variableCostWhenPay(VariableCostWhenPayEnum variableCostWhenPay) {
    this.variableCostWhenPay = variableCostWhenPay;
    return this;
  }

   /**
   * Get variableCostWhenPay
   * @return variableCostWhenPay
  **/
  @ApiModelProperty(example = "null", value = "")
  public VariableCostWhenPayEnum getVariableCostWhenPay() {
    return variableCostWhenPay;
  }

  public void setVariableCostWhenPay(VariableCostWhenPayEnum variableCostWhenPay) {
    this.variableCostWhenPay = variableCostWhenPay;
  }

  public Plan oneTimePlan(Boolean oneTimePlan) {
    this.oneTimePlan = oneTimePlan;
    return this;
  }

   /**
   * Get oneTimePlan
   * @return oneTimePlan
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOneTimePlan() {
    return oneTimePlan;
  }

  public void setOneTimePlan(Boolean oneTimePlan) {
    this.oneTimePlan = oneTimePlan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plan plan = (Plan) o;
    return Objects.equals(this.variableCost, plan.variableCost) &&
        Objects.equals(this.name, plan.name) &&
        Objects.equals(this.oneTimePay, plan.oneTimePay) &&
        Objects.equals(this.hasVariableCost, plan.hasVariableCost) &&
        Objects.equals(this.description, plan.description) &&
        Objects.equals(this.subscription, plan.subscription) &&
        Objects.equals(this.beforePlanId, plan.beforePlanId) &&
        Objects.equals(this.onExpiratyNextPlanId, plan.onExpiratyNextPlanId) &&
        Objects.equals(this.upgradeLevel, plan.upgradeLevel) &&
        Objects.equals(this.requirePaymentMethod, plan.requirePaymentMethod) &&
        Objects.equals(this.id, plan.id) &&
        Objects.equals(this.packId, plan.packId) &&
        Objects.equals(this.typ, plan.typ) &&
        Objects.equals(this.uiOrder, plan.uiOrder) &&
        Objects.equals(this.family, plan.family) &&
        Objects.equals(this.uiVisible, plan.uiVisible) &&
        Objects.equals(this.withfamily, plan.withfamily) &&
        Objects.equals(this.variableCostWhenPay, plan.variableCostWhenPay) &&
        Objects.equals(this.oneTimePlan, plan.oneTimePlan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variableCost, name, oneTimePay, hasVariableCost, description, subscription, beforePlanId, onExpiratyNextPlanId, upgradeLevel, requirePaymentMethod, id, packId, typ, uiOrder, family, uiVisible, withfamily, variableCostWhenPay, oneTimePlan);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plan {\n");
    
    sb.append("    variableCost: ").append(toIndentedString(variableCost)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oneTimePay: ").append(toIndentedString(oneTimePay)).append("\n");
    sb.append("    hasVariableCost: ").append(toIndentedString(hasVariableCost)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("    beforePlanId: ").append(toIndentedString(beforePlanId)).append("\n");
    sb.append("    onExpiratyNextPlanId: ").append(toIndentedString(onExpiratyNextPlanId)).append("\n");
    sb.append("    upgradeLevel: ").append(toIndentedString(upgradeLevel)).append("\n");
    sb.append("    requirePaymentMethod: ").append(toIndentedString(requirePaymentMethod)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    packId: ").append(toIndentedString(packId)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("    uiOrder: ").append(toIndentedString(uiOrder)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    uiVisible: ").append(toIndentedString(uiVisible)).append("\n");
    sb.append("    withfamily: ").append(toIndentedString(withfamily)).append("\n");
    sb.append("    variableCostWhenPay: ").append(toIndentedString(variableCostWhenPay)).append("\n");
    sb.append("    oneTimePlan: ").append(toIndentedString(oneTimePlan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

