/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PricingTablePlan;
import io.swagger.client.model.PricingTableResource;
import java.util.ArrayList;
import java.util.List;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class PricingTablePack   {
  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("resources")
  private List<PricingTableResource> resources = new ArrayList<PricingTableResource>();

  @SerializedName("plans")
  private List<PricingTablePlan> plans = new ArrayList<PricingTablePlan>();

  @SerializedName("title")
  private String title = null;

  public PricingTablePack description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PricingTablePack id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PricingTablePack resources(List<PricingTableResource> resources) {
    this.resources = resources;
    return this;
  }

  public PricingTablePack addResourcesItem(PricingTableResource resourcesItem) {
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PricingTableResource> getResources() {
    return resources;
  }

  public void setResources(List<PricingTableResource> resources) {
    this.resources = resources;
  }

  public PricingTablePack plans(List<PricingTablePlan> plans) {
    this.plans = plans;
    return this;
  }

  public PricingTablePack addPlansItem(PricingTablePlan plansItem) {
    this.plans.add(plansItem);
    return this;
  }

   /**
   * Get plans
   * @return plans
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PricingTablePlan> getPlans() {
    return plans;
  }

  public void setPlans(List<PricingTablePlan> plans) {
    this.plans = plans;
  }

  public PricingTablePack title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingTablePack pricingTablePack = (PricingTablePack) o;
    return Objects.equals(this.description, pricingTablePack.description) &&
        Objects.equals(this.id, pricingTablePack.id) &&
        Objects.equals(this.resources, pricingTablePack.resources) &&
        Objects.equals(this.plans, pricingTablePack.plans) &&
        Objects.equals(this.title, pricingTablePack.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, resources, plans, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingTablePack {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

