/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PricingUiConfPlan;
import io.swagger.client.model.PricingUiConfResource;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class PricingUiConfPack   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("order")
  private Integer order = null;

  @SerializedName("isVisible")
  private Boolean isVisible = null;

  @SerializedName("resources")
  private List<PricingUiConfResource> resources = new ArrayList<PricingUiConfResource>();

  @SerializedName("plans")
  private Map<String, PricingUiConfPlan> plans = new HashMap<String, PricingUiConfPlan>();

  public PricingUiConfPack id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PricingUiConfPack order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public PricingUiConfPack isVisible(Boolean isVisible) {
    this.isVisible = isVisible;
    return this;
  }

   /**
   * Get isVisible
   * @return isVisible
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsVisible() {
    return isVisible;
  }

  public void setIsVisible(Boolean isVisible) {
    this.isVisible = isVisible;
  }

  public PricingUiConfPack resources(List<PricingUiConfResource> resources) {
    this.resources = resources;
    return this;
  }

  public PricingUiConfPack addResourcesItem(PricingUiConfResource resourcesItem) {
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PricingUiConfResource> getResources() {
    return resources;
  }

  public void setResources(List<PricingUiConfResource> resources) {
    this.resources = resources;
  }

  public PricingUiConfPack plans(Map<String, PricingUiConfPlan> plans) {
    this.plans = plans;
    return this;
  }

  public PricingUiConfPack putPlansItem(String key, PricingUiConfPlan plansItem) {
    this.plans.put(key, plansItem);
    return this;
  }

   /**
   * Get plans
   * @return plans
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, PricingUiConfPlan> getPlans() {
    return plans;
  }

  public void setPlans(Map<String, PricingUiConfPlan> plans) {
    this.plans = plans;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingUiConfPack pricingUiConfPack = (PricingUiConfPack) o;
    return Objects.equals(this.id, pricingUiConfPack.id) &&
        Objects.equals(this.order, pricingUiConfPack.order) &&
        Objects.equals(this.isVisible, pricingUiConfPack.isVisible) &&
        Objects.equals(this.resources, pricingUiConfPack.resources) &&
        Objects.equals(this.plans, pricingUiConfPack.plans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, order, isVisible, resources, plans);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingUiConfPack {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    isVisible: ").append(toIndentedString(isVisible)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

