/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class PricingUiConfPlan   {
  /**
   * Gets or Sets mainPrice
   */
  public enum MainPriceEnum {
    @SerializedName("VariableCost")
    VARIABLECOST("VariableCost"),
    
    @SerializedName("PeriodicCost")
    PERIODICCOST("PeriodicCost"),
    
    @SerializedName("Setup")
    SETUP("Setup"),
    
    @SerializedName("Cost")
    COST("Cost");

    private String value;

    MainPriceEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("mainPrice")
  private MainPriceEnum mainPrice = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("order")
  private Integer order = null;

  @SerializedName("isVisible")
  private Boolean isVisible = null;

  @SerializedName("mainVariableCost")
  private String mainVariableCost = null;

  /**
   * Gets or Sets period
   */
  public enum PeriodEnum {
    @SerializedName("Year")
    YEAR("Year"),
    
    @SerializedName("Month")
    MONTH("Month"),
    
    @SerializedName("Week")
    WEEK("Week"),
    
    @SerializedName("Day")
    DAY("Day");

    private String value;

    PeriodEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("period")
  private PeriodEnum period = null;

  public PricingUiConfPlan mainPrice(MainPriceEnum mainPrice) {
    this.mainPrice = mainPrice;
    return this;
  }

   /**
   * Get mainPrice
   * @return mainPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public MainPriceEnum getMainPrice() {
    return mainPrice;
  }

  public void setMainPrice(MainPriceEnum mainPrice) {
    this.mainPrice = mainPrice;
  }

  public PricingUiConfPlan id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PricingUiConfPlan order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public PricingUiConfPlan isVisible(Boolean isVisible) {
    this.isVisible = isVisible;
    return this;
  }

   /**
   * Get isVisible
   * @return isVisible
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsVisible() {
    return isVisible;
  }

  public void setIsVisible(Boolean isVisible) {
    this.isVisible = isVisible;
  }

  public PricingUiConfPlan mainVariableCost(String mainVariableCost) {
    this.mainVariableCost = mainVariableCost;
    return this;
  }

   /**
   * Get mainVariableCost
   * @return mainVariableCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMainVariableCost() {
    return mainVariableCost;
  }

  public void setMainVariableCost(String mainVariableCost) {
    this.mainVariableCost = mainVariableCost;
  }

  public PricingUiConfPlan period(PeriodEnum period) {
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  @ApiModelProperty(example = "null", value = "")
  public PeriodEnum getPeriod() {
    return period;
  }

  public void setPeriod(PeriodEnum period) {
    this.period = period;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingUiConfPlan pricingUiConfPlan = (PricingUiConfPlan) o;
    return Objects.equals(this.mainPrice, pricingUiConfPlan.mainPrice) &&
        Objects.equals(this.id, pricingUiConfPlan.id) &&
        Objects.equals(this.order, pricingUiConfPlan.order) &&
        Objects.equals(this.isVisible, pricingUiConfPlan.isVisible) &&
        Objects.equals(this.mainVariableCost, pricingUiConfPlan.mainVariableCost) &&
        Objects.equals(this.period, pricingUiConfPlan.period);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mainPrice, id, order, isVisible, mainVariableCost, period);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingUiConfPlan {\n");
    
    sb.append("    mainPrice: ").append(toIndentedString(mainPrice)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    isVisible: ").append(toIndentedString(isVisible)).append("\n");
    sb.append("    mainVariableCost: ").append(toIndentedString(mainVariableCost)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

