/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Plan;
import io.swagger.client.model.PricingPolicy;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class PricingConf   {
  @SerializedName("currencies")
  private List<String> currencies = new ArrayList<String>();

  @SerializedName("defaultCurrency")
  private String defaultCurrency = null;

  @SerializedName("plans")
  private Map<String, Plan> plans = new HashMap<String, Plan>();

  @SerializedName("policy")
  private PricingPolicy policy = null;

  public PricingConf currencies(List<String> currencies) {
    this.currencies = currencies;
    return this;
  }

  public PricingConf addCurrenciesItem(String currenciesItem) {
    this.currencies.add(currenciesItem);
    return this;
  }

   /**
   * Get currencies
   * @return currencies
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getCurrencies() {
    return currencies;
  }

  public void setCurrencies(List<String> currencies) {
    this.currencies = currencies;
  }

  public PricingConf defaultCurrency(String defaultCurrency) {
    this.defaultCurrency = defaultCurrency;
    return this;
  }

   /**
   * Get defaultCurrency
   * @return defaultCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultCurrency() {
    return defaultCurrency;
  }

  public void setDefaultCurrency(String defaultCurrency) {
    this.defaultCurrency = defaultCurrency;
  }

  public PricingConf plans(Map<String, Plan> plans) {
    this.plans = plans;
    return this;
  }

  public PricingConf putPlansItem(String key, Plan plansItem) {
    this.plans.put(key, plansItem);
    return this;
  }

   /**
   * Get plans
   * @return plans
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Plan> getPlans() {
    return plans;
  }

  public void setPlans(Map<String, Plan> plans) {
    this.plans = plans;
  }

  public PricingConf policy(PricingPolicy policy) {
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @ApiModelProperty(example = "null", value = "")
  public PricingPolicy getPolicy() {
    return policy;
  }

  public void setPolicy(PricingPolicy policy) {
    this.policy = policy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingConf pricingConf = (PricingConf) o;
    return Objects.equals(this.currencies, pricingConf.currencies) &&
        Objects.equals(this.defaultCurrency, pricingConf.defaultCurrency) &&
        Objects.equals(this.plans, pricingConf.plans) &&
        Objects.equals(this.policy, pricingConf.policy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencies, defaultCurrency, plans, policy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingConf {\n");
    
    sb.append("    currencies: ").append(toIndentedString(currencies)).append("\n");
    sb.append("    defaultCurrency: ").append(toIndentedString(defaultCurrency)).append("\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

