/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class ResourcePatchResult   {
  @SerializedName("isOk")
  private Boolean isOk = null;

  @SerializedName("oldValue")
  private Long oldValue = null;

  @SerializedName("actualValue")
  private Long actualValue = null;

  public ResourcePatchResult isOk(Boolean isOk) {
    this.isOk = isOk;
    return this;
  }

   /**
   * Get isOk
   * @return isOk
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsOk() {
    return isOk;
  }

  public void setIsOk(Boolean isOk) {
    this.isOk = isOk;
  }

  public ResourcePatchResult oldValue(Long oldValue) {
    this.oldValue = oldValue;
    return this;
  }

   /**
   * Get oldValue
   * @return oldValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getOldValue() {
    return oldValue;
  }

  public void setOldValue(Long oldValue) {
    this.oldValue = oldValue;
  }

  public ResourcePatchResult actualValue(Long actualValue) {
    this.actualValue = actualValue;
    return this;
  }

   /**
   * Get actualValue
   * @return actualValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getActualValue() {
    return actualValue;
  }

  public void setActualValue(Long actualValue) {
    this.actualValue = actualValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourcePatchResult resourcePatchResult = (ResourcePatchResult) o;
    return Objects.equals(this.isOk, resourcePatchResult.isOk) &&
        Objects.equals(this.oldValue, resourcePatchResult.oldValue) &&
        Objects.equals(this.actualValue, resourcePatchResult.actualValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isOk, oldValue, actualValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourcePatchResult {\n");
    
    sb.append("    isOk: ").append(toIndentedString(isOk)).append("\n");
    sb.append("    oldValue: ").append(toIndentedString(oldValue)).append("\n");
    sb.append("    actualValue: ").append(toIndentedString(actualValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

