/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class StripeCustomer   {
  @SerializedName("creditToken")
  private String creditToken = null;

  @SerializedName("client_id")
  private String clientId = null;

  @SerializedName("defaultCardLast4")
  private String defaultCardLast4 = null;

  @SerializedName("defaultExpMonth")
  private Integer defaultExpMonth = null;

  @SerializedName("defaultExpYear")
  private Integer defaultExpYear = null;

  public StripeCustomer creditToken(String creditToken) {
    this.creditToken = creditToken;
    return this;
  }

   /**
   * Get creditToken
   * @return creditToken
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreditToken() {
    return creditToken;
  }

  public void setCreditToken(String creditToken) {
    this.creditToken = creditToken;
  }

  public StripeCustomer clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public StripeCustomer defaultCardLast4(String defaultCardLast4) {
    this.defaultCardLast4 = defaultCardLast4;
    return this;
  }

   /**
   * Get defaultCardLast4
   * @return defaultCardLast4
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultCardLast4() {
    return defaultCardLast4;
  }

  public void setDefaultCardLast4(String defaultCardLast4) {
    this.defaultCardLast4 = defaultCardLast4;
  }

  public StripeCustomer defaultExpMonth(Integer defaultExpMonth) {
    this.defaultExpMonth = defaultExpMonth;
    return this;
  }

   /**
   * Get defaultExpMonth
   * @return defaultExpMonth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDefaultExpMonth() {
    return defaultExpMonth;
  }

  public void setDefaultExpMonth(Integer defaultExpMonth) {
    this.defaultExpMonth = defaultExpMonth;
  }

  public StripeCustomer defaultExpYear(Integer defaultExpYear) {
    this.defaultExpYear = defaultExpYear;
    return this;
  }

   /**
   * Get defaultExpYear
   * @return defaultExpYear
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDefaultExpYear() {
    return defaultExpYear;
  }

  public void setDefaultExpYear(Integer defaultExpYear) {
    this.defaultExpYear = defaultExpYear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StripeCustomer stripeCustomer = (StripeCustomer) o;
    return Objects.equals(this.creditToken, stripeCustomer.creditToken) &&
        Objects.equals(this.clientId, stripeCustomer.clientId) &&
        Objects.equals(this.defaultCardLast4, stripeCustomer.defaultCardLast4) &&
        Objects.equals(this.defaultExpMonth, stripeCustomer.defaultExpMonth) &&
        Objects.equals(this.defaultExpYear, stripeCustomer.defaultExpYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditToken, clientId, defaultCardLast4, defaultExpMonth, defaultExpYear);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StripeCustomer {\n");
    
    sb.append("    creditToken: ").append(toIndentedString(creditToken)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    defaultCardLast4: ").append(toIndentedString(defaultCardLast4)).append("\n");
    sb.append("    defaultExpMonth: ").append(toIndentedString(defaultExpMonth)).append("\n");
    sb.append("    defaultExpYear: ").append(toIndentedString(defaultExpYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

