/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class UserUiConf   {
  @SerializedName("googleClientId")
  private String googleClientId = null;

  @SerializedName("googleClientKey")
  private String googleClientKey = null;

  @SerializedName("loginUrl")
  private String loginUrl = null;

  @SerializedName("basePath")
  private String basePath = null;

  @SerializedName("changePasswordUrl")
  private String changePasswordUrl = null;

  @SerializedName("registerUrl")
  private String registerUrl = null;

  @SerializedName("recoverPasswordUrl")
  private String recoverPasswordUrl = null;

  @SerializedName("loginHandler")
  private String loginHandler = null;

  @SerializedName("subscribeUrl")
  private String subscribeUrl = null;

  public UserUiConf googleClientId(String googleClientId) {
    this.googleClientId = googleClientId;
    return this;
  }

   /**
   * Get googleClientId
   * @return googleClientId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGoogleClientId() {
    return googleClientId;
  }

  public void setGoogleClientId(String googleClientId) {
    this.googleClientId = googleClientId;
  }

  public UserUiConf googleClientKey(String googleClientKey) {
    this.googleClientKey = googleClientKey;
    return this;
  }

   /**
   * Get googleClientKey
   * @return googleClientKey
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGoogleClientKey() {
    return googleClientKey;
  }

  public void setGoogleClientKey(String googleClientKey) {
    this.googleClientKey = googleClientKey;
  }

  public UserUiConf loginUrl(String loginUrl) {
    this.loginUrl = loginUrl;
    return this;
  }

   /**
   * Get loginUrl
   * @return loginUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLoginUrl() {
    return loginUrl;
  }

  public void setLoginUrl(String loginUrl) {
    this.loginUrl = loginUrl;
  }

  public UserUiConf basePath(String basePath) {
    this.basePath = basePath;
    return this;
  }

   /**
   * Get basePath
   * @return basePath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBasePath() {
    return basePath;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public UserUiConf changePasswordUrl(String changePasswordUrl) {
    this.changePasswordUrl = changePasswordUrl;
    return this;
  }

   /**
   * Get changePasswordUrl
   * @return changePasswordUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChangePasswordUrl() {
    return changePasswordUrl;
  }

  public void setChangePasswordUrl(String changePasswordUrl) {
    this.changePasswordUrl = changePasswordUrl;
  }

  public UserUiConf registerUrl(String registerUrl) {
    this.registerUrl = registerUrl;
    return this;
  }

   /**
   * Get registerUrl
   * @return registerUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegisterUrl() {
    return registerUrl;
  }

  public void setRegisterUrl(String registerUrl) {
    this.registerUrl = registerUrl;
  }

  public UserUiConf recoverPasswordUrl(String recoverPasswordUrl) {
    this.recoverPasswordUrl = recoverPasswordUrl;
    return this;
  }

   /**
   * Get recoverPasswordUrl
   * @return recoverPasswordUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRecoverPasswordUrl() {
    return recoverPasswordUrl;
  }

  public void setRecoverPasswordUrl(String recoverPasswordUrl) {
    this.recoverPasswordUrl = recoverPasswordUrl;
  }

  public UserUiConf loginHandler(String loginHandler) {
    this.loginHandler = loginHandler;
    return this;
  }

   /**
   * Get loginHandler
   * @return loginHandler
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLoginHandler() {
    return loginHandler;
  }

  public void setLoginHandler(String loginHandler) {
    this.loginHandler = loginHandler;
  }

  public UserUiConf subscribeUrl(String subscribeUrl) {
    this.subscribeUrl = subscribeUrl;
    return this;
  }

   /**
   * Get subscribeUrl
   * @return subscribeUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubscribeUrl() {
    return subscribeUrl;
  }

  public void setSubscribeUrl(String subscribeUrl) {
    this.subscribeUrl = subscribeUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUiConf userUiConf = (UserUiConf) o;
    return Objects.equals(this.googleClientId, userUiConf.googleClientId) &&
        Objects.equals(this.googleClientKey, userUiConf.googleClientKey) &&
        Objects.equals(this.loginUrl, userUiConf.loginUrl) &&
        Objects.equals(this.basePath, userUiConf.basePath) &&
        Objects.equals(this.changePasswordUrl, userUiConf.changePasswordUrl) &&
        Objects.equals(this.registerUrl, userUiConf.registerUrl) &&
        Objects.equals(this.recoverPasswordUrl, userUiConf.recoverPasswordUrl) &&
        Objects.equals(this.loginHandler, userUiConf.loginHandler) &&
        Objects.equals(this.subscribeUrl, userUiConf.subscribeUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(googleClientId, googleClientKey, loginUrl, basePath, changePasswordUrl, registerUrl, recoverPasswordUrl, loginHandler, subscribeUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUiConf {\n");
    
    sb.append("    googleClientId: ").append(toIndentedString(googleClientId)).append("\n");
    sb.append("    googleClientKey: ").append(toIndentedString(googleClientKey)).append("\n");
    sb.append("    loginUrl: ").append(toIndentedString(loginUrl)).append("\n");
    sb.append("    basePath: ").append(toIndentedString(basePath)).append("\n");
    sb.append("    changePasswordUrl: ").append(toIndentedString(changePasswordUrl)).append("\n");
    sb.append("    registerUrl: ").append(toIndentedString(registerUrl)).append("\n");
    sb.append("    recoverPasswordUrl: ").append(toIndentedString(recoverPasswordUrl)).append("\n");
    sb.append("    loginHandler: ").append(toIndentedString(loginHandler)).append("\n");
    sb.append("    subscribeUrl: ").append(toIndentedString(subscribeUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

