/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.VariableCostIntervalCost;
import io.swagger.client.model.VariableCostIntervalPerUnit;
import io.swagger.client.model.VariableCostPerUnit;


/**
 * Model description
 */
@ApiModel(description = "Model description")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-04T14:36:36.360Z")
public class VariableCost   {
  @SerializedName("resourceId")
  private String resourceId = null;

  @SerializedName("perUnit")
  private VariableCostPerUnit perUnit = null;

  @SerializedName("intervalCost")
  private VariableCostIntervalCost intervalCost = null;

  @SerializedName("intervalPerUnit")
  private VariableCostIntervalPerUnit intervalPerUnit = null;

  /**
   * Gets or Sets typ
   */
  public enum TypEnum {
    @SerializedName("IntervalCost")
    INTERVALCOST("IntervalCost"),
    
    @SerializedName("IntervalPerUnit")
    INTERVALPERUNIT("IntervalPerUnit"),
    
    @SerializedName("PerUnit")
    PERUNIT("PerUnit"),
    
    @SerializedName("NoCost")
    NOCOST("NoCost");

    private String value;

    TypEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("typ")
  private TypEnum typ = null;

  public VariableCost resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public VariableCost perUnit(VariableCostPerUnit perUnit) {
    this.perUnit = perUnit;
    return this;
  }

   /**
   * Get perUnit
   * @return perUnit
  **/
  @ApiModelProperty(example = "null", value = "")
  public VariableCostPerUnit getPerUnit() {
    return perUnit;
  }

  public void setPerUnit(VariableCostPerUnit perUnit) {
    this.perUnit = perUnit;
  }

  public VariableCost intervalCost(VariableCostIntervalCost intervalCost) {
    this.intervalCost = intervalCost;
    return this;
  }

   /**
   * Get intervalCost
   * @return intervalCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public VariableCostIntervalCost getIntervalCost() {
    return intervalCost;
  }

  public void setIntervalCost(VariableCostIntervalCost intervalCost) {
    this.intervalCost = intervalCost;
  }

  public VariableCost intervalPerUnit(VariableCostIntervalPerUnit intervalPerUnit) {
    this.intervalPerUnit = intervalPerUnit;
    return this;
  }

   /**
   * Get intervalPerUnit
   * @return intervalPerUnit
  **/
  @ApiModelProperty(example = "null", value = "")
  public VariableCostIntervalPerUnit getIntervalPerUnit() {
    return intervalPerUnit;
  }

  public void setIntervalPerUnit(VariableCostIntervalPerUnit intervalPerUnit) {
    this.intervalPerUnit = intervalPerUnit;
  }

  public VariableCost typ(TypEnum typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypEnum getTyp() {
    return typ;
  }

  public void setTyp(TypEnum typ) {
    this.typ = typ;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableCost variableCost = (VariableCost) o;
    return Objects.equals(this.resourceId, variableCost.resourceId) &&
        Objects.equals(this.perUnit, variableCost.perUnit) &&
        Objects.equals(this.intervalCost, variableCost.intervalCost) &&
        Objects.equals(this.intervalPerUnit, variableCost.intervalPerUnit) &&
        Objects.equals(this.typ, variableCost.typ);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceId, perUnit, intervalCost, intervalPerUnit, typ);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableCost {\n");
    
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    perUnit: ").append(toIndentedString(perUnit)).append("\n");
    sb.append("    intervalCost: ").append(toIndentedString(intervalCost)).append("\n");
    sb.append("    intervalPerUnit: ").append(toIndentedString(intervalPerUnit)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

