/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.S4sError;
import io.swagger.client.model.ResourcePatch;
import io.swagger.client.model.ResourcePatchResult;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SsResourceApi
 */
public class SsResourceApiTest {

    private final SsResourceApi api = new SsResourceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerResourceGetTest() throws ApiException {
        String customerId = null;
        String resourceid = null;
        // Long response = api.customerResourceGet(customerId, resourceid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerResourceLimitGetTest() throws ApiException {
        String customerId = null;
        String resourceid = null;
        // Long response = api.customerResourceLimitGet(customerId, resourceid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Updates a resource of a customer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerResourcePatchTest() throws ApiException {
        String customerId = null;
        String resourceid = null;
        ResourcePatch value = null;
        // ResourcePatchResult response = api.customerResourcePatch(customerId, resourceid, value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerResourceProductGetTest() throws ApiException {
        String customerId = null;
        String resourceid = null;
        String customerProductId = null;
        // Long response = api.customerResourceProductGet(customerId, resourceid, customerProductId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerResourceProductLimitGetTest() throws ApiException {
        String customerId = null;
        String resourceid = null;
        String customerProductId = null;
        // Long response = api.customerResourceProductLimitGet(customerId, resourceid, customerProductId);

        // TODO: test validations
    }
    
}
